.TH l_adsidentity 8 "2011 Apr 8" Lustre "utilities"
.SH NAME
l_adsidentity \- handles AD user/group cache upcall
.SH SYNOPSIS
.B        "l_adsidentity mdtname uid"
.SH DESCRIPTION
The identity_upcall file contains the path to an executable file that, 
when properly installed, is invoked to resolve a numeric UID to an
Active Directory(AD) groups membership list. This utility should complete the identity_downcall_data structure and write it to the 
/proc/fs/lustre/mdt/${FSNAME}-MDT{xxxx}/identity_info pseudo-file.
        
The l_adsidentity utility is the reference implementation of the user
or group cache upcall.

The Lustre administrator should specify permissions for a specific UID by
configuring /etc/lustre/perm.conf on the MDS and AD server details in
/etc/lustre/ads.conf.

set L_ADSIDENTITY_TEST environment variable to test from the command
line. This test lists out the all the user permissions and AD groups
membership details on to console.
.SH FILES
/proc/fs/lustre/mdt/${FSNAME}-MDT{xxxx}/identity_upcall
.SH EXAMPLES
        #l_adsidentity lustre-MDT0000 10001
        uid=10001 gid=10002,10003
        permissions:
          nid                   perm
          0xffffffffffffffff    0xf        
.SH SEE ALSO
Lustre Programming Interfaces section of Lustre Operations Manual.
